# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0
version: 2
updates:
# Composer
- package-ecosystem: composer
  directory: "/"
  commit-message:
    prefix: "ci"
    include: "scope"
  versioning-strategy: "increase"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Berlin

# GitHub Actions
- package-ecosystem: "github-actions"
  directory: ".github/workflows"
  commit-message:
    prefix: "ci"
    include: "scope"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Berlin
